"""empty message

Revision ID: 096aa3bf99d5
Revises: cccb4b5e7ba5
Create Date: 2016-09-12 14:25:27.266002

"""

# revision identifiers, used by Alembic.
revision = '096aa3bf99d5'
down_revision = 'cccb4b5e7ba5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydraurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hydra_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hydra_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hydra_url_id', sa.Integer(), nullable=False),
    sa.Column('hydra_userid', sa.Integer(), nullable=False),
    sa.Column('hydra_username', sa.String(length=50), nullable=False),
    sa.Column('hydra_password', sa.String(length=255), nullable=False),
    sa.Column('hydra_sessionid', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hydra_url_id'], ['hydraurl.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hydra_url_id', 'hydra_userid')
    )
    op.drop_table('hydra_url')
    op.add_column('user', sa.Column('new_user', sa.Boolean(), server_default='1', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'new_user')
    op.create_table('hydra_url',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hydra_url', sa.VARCHAR(length=255), server_default=sa.text("''"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hydra_user')
    op.drop_table('hydraurl')
    ### end Alembic commands ###
