"""empty message

Revision ID: 8d13fea0e259
Revises: None
Create Date: 2016-09-13 18:46:13.755694

"""

# revision identifiers, used by Alembic.
revision = '8d13fea0e259'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hydraurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hydra_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('new_user', sa.Boolean(), server_default='1', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('hydraproj',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hydra_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hydra_project_id')
    )
    op.create_table('hydrauser',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hydra_url_id', sa.Integer(), nullable=False),
    sa.Column('hydra_userid', sa.Integer(), nullable=False),
    sa.Column('hydra_username', sa.String(length=50), nullable=False),
    sa.Column('hydra_password', sa.String(length=255), nullable=False),
    sa.Column('hydra_sessionid', sa.String(length=255), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['hydra_url_id'], ['hydraurl.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'hydra_url_id', 'hydra_userid')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('hydrauser')
    op.drop_table('hydraproj')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('hydraurl')
    ### end Alembic commands ###
