"""empty message

Revision ID: e6ba3f4eba8d
Revises: None
Create Date: 2016-09-05 19:28:45.988860

"""

# revision identifiers, used by Alembic.
revision = 'e6ba3f4eba8d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization', sa.String(length=100), server_default='', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organization')
    ### end Alembic commands ###
